# fly.toml app configuration file generated for bus-packet-generator on 2023-08-02T11:04:07-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bus-packet-generator"
primary_region = "bos"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
